- name: Restart AmneziaWG
  systemd:
    name: "{{ vpn_service_name }}"
    state: restarted
  become: true

- name: Save iptables rules
  shell: |
    set -o pipefail
    iptables-save  | grep -v 'f2b-' > /etc/iptables/rules.v4
    ip6tables-save | grep -v 'f2b-' > /etc/iptables/rules.v6
  become: true
  changed_when: true
